app_name: "My Sample App"
version: 1.0
debug_mode: true

database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "secret_password"

logging:
  level: "INFO"
  file: "app.log"

features:
  enable_feature_a: true
  enable_feature_b: false

server:
    host: "0.0.0.0"
    port: 8080

api:
    url: "https://api.example.com"
    timeout: 30
